query ArticlesBySlug($slug: String!) {
  articleCollection(where: { slug: $slug }) {
    items {
      title
      content
      tag
      slug
      date
      category
    }
  }
}

query ArticleSlugs($limit: Int, $skip: Int) {
  articleCollection(
    # The default is 100 and the maximum is 1000
    limit: $limit,
    skip: $skip
  ) {
    total
    skip
    limit
    items {
      slug
    }
  }
}
